name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global https://vercel-50m13gr84.vercel.sh/tarballs/vercel.tgz # 20MB chunks (needs --archive too)
        # run: npm install --global https://vercel-dckw3egfv.vercel.sh/tarballs/vercel.tgz # dont reuse sockets

      - name: Install bun
        run: npm install --global bun@latest
      - name: run build
        run: bun run build
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy -d --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz # with archive
        # run: vercel deploy -d --token=${{ secrets.VERCEL_TOKEN }} # without
